title: Cheewin's Portfolio
#description: Data Scientist | Data Analyst | Business Analyst
show_downloads: false
google_analytics:
logo: https://raw.githubusercontent.com/cwnstae/cwnstae.github.io/main/assets/my%20profile%20picture.png
theme: jekyll-theme-minimal
